### PR TITLE
Documentation merge conflicts fixed

### PR DESCRIPTION
**Pull request by jeremiah**
Various merge conflicts fixed - now only two files to merge; one new, one slightly modified.

### CODE REVIEW

**Comment by ximion** [comment]
Can you convert the document to reStructuredText and move it to a location where Sphinx will pick it up for documentation generation? `docs/general` seems like the right place.

**Comment by jeremiah** [comment]
The static checks passed on my system (the container was at least successfully built for Debian Testing.)

**Comment by ximion** [comment]
Looked good (and is merged), but wasn't this a larger change once, with a whole setup document? the stuff that I just merged was mostly typo fixes...

**Comment by jeremiah** [comment]
Yes, there is a whole setup document - that was the one that got moved under the docs/general dir as .rst so that ReadtheDocs can pick it up. It was updated by you so my changes to that doc were pretty small.

**Pull request merged**
